2021/02/21 12:42:13 : Traceback (most recent call last):
  File "/var/www/python/cartmigration/models/basecart.py", line 1325, in gzinflate
    res = zlib.decompress(compressed_data, -15)
zlib.error: Error -3 while decompressing data: invalid block type

2021/02/21 12:42:13 : Traceback (most recent call last):
  File "/var/www/python/cartmigration/models/basecart.py", line 1325, in gzinflate
    res = zlib.decompress(compressed_data, -15)
zlib.error: Error -3 while decompressing data: invalid block type

